#!/usr/bin/env node

var spawnSync = require('child_process').spawnSync
var chalk = require('chalk')
var fs = require('fs')

var filePath = process.argv[2]
var best = {
  value: '',
  size: Infinity
}
var lastString

function shuffle (a) {
  var j, x, i
  for (i = a.length - 1; i > 0; i--) {
    j = Math.floor(Math.random() * (i + 1))
    x = a[i]
    a[i] = a[j]
    a[j] = x
  }
  return a
}

function saveFirstString () {
  var data = fs.readFileSync(filePath, 'utf8')
  data.replace(/[A-Za-z0-9~_]{58}/g, function (match) {
    lastString = match
  })
}

function shuffleStringInFile () {
  var data = fs.readFileSync(filePath, 'utf8')

  var result = data.replace(/[A-Za-z0-9~_]{64}/g, function (match) {
    lastString = shuffle(match.split('')).join('')
    return lastString
  })

  fs.writeFileSync(filePath + '', result, 'utf8')
}

function checkSize () {
  var output = spawnSync('npx', ['size-limit', filePath]).output
  var size = output.toString('utf8').match(/Package size: ([0-9]+)/)
  if (size && size[1] !== 0 && size[1] < best.size) {
    best.value = lastString
    best.size = size[1]
    process.stdout.write(chalk.green.bold(best.size) + 'B ' + best.value + '\n')
  }
}

saveFirstString()
if (typeof lastString === 'undefined') {
  process.stderr.write(chalk.red('Alphabet was not found') + '\n')
  process.exit(1)
}
checkSize()

while (true) {
  shuffleStringInFile()
  checkSize()
}
