#!/usr/bin/env node

var UglifyJS = require('uglify-js')
var gzipSize = require('gzip-size')
var chalk = require('chalk')
var path = require('path')
var fs = require('fs')

var filePath = path.join(process.cwd(), process.argv[2])
var file
var used = { }

function shuffle (str) {
  var array = str.split('')
  var j, x, i
  for (i = array.length - 1; i > 0; i--) {
    j = Math.floor(Math.random() * (i + 1))
    x = array[i]
    array[i] = array[j]
    array[j] = x
  }
  return array.join('')
}

function shuffleUnique (str) {
  var mixed
  while (true) {
    mixed = shuffle(str)
    if (!used[mixed]) {
      used[mixed] = true
      return mixed
    }
  }
}

function factorial (number) {
  var total = 1
  while (number > 0) {
    total *= number
    number = number - 1
  }
  return total
}

var best = {
  value: '',
  size: Infinity
}
var lastString
var step = 0
var prevPercent = 0
var maxSteps = factorial(64)

function findInitialString () {
  file = fs.readFileSync(filePath, 'utf8')
  file = UglifyJS.minify(file).code.replace('module.', 'e.')
  file = '!function(e){var t={};function r(n){if(t[n])return t[n].exports;' +
          'var o=t[n]={i:n,l:!1,exports:{}};return ' +
          'e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}' +
          'r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||' +
          'Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){' +
          '"undefined"!=typeof Symbol&&Symbol.toStringTag&&' +
          'Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),' +
          'Object.defineProperty(e,"__esModule",{value:!0})},' +
          'r.t=function(e,t){if(1&t&&(e=r(e)),8&t)' +
          'return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;' +
          'var n=Object.create(null);if(r.r(n),Object.defineProperty(' +
          'n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)' +
          'for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));' +
          'return n},r.n=function(e){var t=e&&e.__esModule?function(){' +
          'return e.default}:function(){return e};return r.d(t,"a",t),t}' +
          ',r.o=function(e,t){return Object.prototype.hasOwnProperty' +
          '.call(e,t)},r.p="",r(r.s=0)}([function(e,t){' + file + '}]);'
  var match = file.match(/[A-Za-z0-9~_]{64}/)
  if (!match) {
    process.stderr.write(chalk.red('Alphabet was not found') + '\n')
    process.exit(1)
  }
  lastString = match[0]
}

function shuffleString () {
  lastString = shuffleUnique(lastString)
  file = file.replace(/[A-Za-z0-9~_]{64}/, lastString)
}

function checkSize () {
  step += 1
  gzipSize(file).then(function (size) {
    size = size - 461
    if (size < best.size) {
      best.value = lastString
      best.size = size
      process.stdout.write(
        chalk.green.bold(best.size + 'B') + ' ' + best.value + '\n')
    } else {
      var percent = Math.floor(10000 * step / maxSteps)
      if (percent > prevPercent) {
        prevPercent = percent
        process.stdout.write(chalk.gray((percent / 10000.0) + '%') + '\n')
      }
    }
    if (step === maxSteps) {
      process.exit(0)
    } else {
      shuffleString()
      checkSize()
    }
  })
}

findInitialString()
checkSize()
