name: Benchmark
on:
  push:
    tags:
      - '*'
  pull_request:
permissions:
  contents: read
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js & pnpm
        uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0
        with:
          version: 11.10.0
          runtime: node@26
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Run benchmark
        run: node ./test/benchmark.js
