name: Test
on:
  push:
    branches:
      - main
      - v3
  pull_request:
permissions:
  contents: read
jobs:
  full:
    name: Node.js Latest Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Node.js & pnpm
        uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0
        with:
          version: 11
          runtime: node@26
      - name: Install dependencies
        run: pnpm ci
      - name: Run tests
        run: pnpm test
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 24
          - 22
    name: Node.js ${{ matrix.node }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Node.js & pnpm
        uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0
        with:
          version: 11
          runtime: node@${{ matrix.node }}
      - name: Install dependencies
        run: pnpm ci
      - name: Run unit tests
        run: pnpm bnt
